services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: my_database  
    volumes:
      - C:\Users\kingh\Documents\Workspace\be_DATN\db:/data/db
    ports:
      - "27017:27017"